### ISSUE TITLE
Apply a static code analyzer

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/infrastructure-as-types#20]
We used https://github.com/wartremover/wartremover in the previous project:

```scala
wartremoverWarnings in (Compile, compile) := {
      import Wart._
      Seq(AnyVal, ArrayEquals, EitherProjectionPartial, FinalCaseClass, IsInstanceOf, JavaConversions,
        LeakingSealed, NonUnitStatements, Null, Recursion, Return, StringPlusAny, ToString)
    },
```

TBD: possibly better/more suitable alternatives exist.

**Comment by pawelprazak** [comment]
Have you tried it? How many hits did we have? ;P

**Comment by PawelLipski** [comment]
Just around ~25 across the project (although I skipped `FinalCaseClass` and `StringPlusAny`)
